make target names more clear
NilFoundation/zkLLVM pull request #526
Opened 2024-02-12 12:37 UTC by CblPOK-git

2024-02-12 15:04 UTC, akokoshn requested changes

2024-02-12 15:04 UTC, akokoshn commented on README.md
> +make -C ${ZKLLVM_BUILD:-build} arithmerics_cpp_example -j$(nproc)
typo, do you mean `arithmetics_cpp_example`

2024-02-12 15:25 UTC, akokoshn approved these changes

2024-02-13 08:59 UTC, aleasims commented on .github/workflows/build_linux.yml
> +      - name: Build assignmen tables(.tbl) of the C++ examples
Small typo: assignment

2024-02-13 11:24 UTC, makxenov commented on .github/workflows/build_macos.yml
> +      - name: Build assignmen tables(.tbl) of the Rust examples
Typo again

2024-02-13 11:32 UTC, makxenov approved these changes

2024-02-13 13:27 UTC, merged

2024-02-13 15:50 UTC, aleasims commented
Just a note:

`PRIVATE_INPUT_ARG` is now handling in `add_rust_example_without_proving`, but Rust compiler does not support private inputs now. It's OK, but don't be confused with that, we still don't have private inputs in Rust.